# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9ba7a1b3989d12d94f6ca594b725d0e34af6711ba18a4dbe11638d53b3bbbf5f74a5fd590780e5805e05051a5c7e8710eb91fad111cc43dfcc11dfff50cc1ca

test:
  secret_key_base: 4446d4a97de77157abcae910e1bddb88157bf56ad5ca927a53de0cbbe2a9498de235a8e80dd8930e756d508eb5d22436121e994e78b81488e287f3cbf1abdc4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
